# Generated by Django 6.0.3 on 2026-03-27 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('health', 'Health'), ('agriculture', 'Agriculture'), ('mining', 'Mining'), ('agrochemicals', 'Agrochemicals'), ('infrastructure', 'Infrastructure'), ('hospitality', 'Hospitality'), ('telemast', 'Telemast')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('file_number', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('type_of_undertaking', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('type_of_application', models.CharField(blank=True, max_length=255)),
                ('date_of_invoice', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_of_submission', models.DateField(blank=True, null=True)),
                ('date_received_from_rg', models.DateField(blank=True, null=True)),
                ('date_of_permit_issued', models.DateField(blank=True, null=True)),
                ('permit_number', models.CharField(blank=True, max_length=100)),
                ('permit_expiry_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
