# Generated by Django 6.0.3 on 2026-03-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(choices=[('health', 'Health'), ('agriculture', 'Agriculture'), ('mining', 'Mining'), ('agrochemicals', 'Agrochemicals'), ('infrastructure', 'Infrastructure'), ('hospitality', 'Hospitality'), ('telemast', 'Telemast'), ('energy', 'Energy')], max_length=20),
        ),
    ]
